import Navbar from '@/components/Navbar';
import Provider from '@/components/Provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LightHosting',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='hu'>
      <body className={inter.className}>
        <Provider>
          <ThemeProvider 
            attribute='class'
            defaultTheme='dark'
            enableSystem={true}
            themes={['light', 'dark']}
            disableTransitionOnChange={true}>
            {children}
          </ThemeProvider>
        </Provider>
          <Toaster />
      </body>
    </html>
  );
}
